### PR TITLE
Provide cleanup method for polling manager

### PR DESCRIPTION
**Pull request by thebongy**
Currently, there's no externally expose API to cleanup the `setInterval()` created by the polling manager class. This PR introduces a external close() method to provide this functionality

### CODE REVIEW

**Comment by matthewelwell** [comment]
This is great, thanks @thebongy. I'm just wondering what the intended use looks like for this method? The reason I ask is that I'm keen for the users of the library to not have to worry about this. For example, in the python client, we handle this by overriding the `__del__` method on the flagsmith client which ensures that the polling manager is always stopped whenever the flagsmith client object is removed from memory. 

https://github.com/Flagsmith/flagsmith-python-client/blob/main/flagsmith/flagsmith.py#L256

**Comment by thebongy** [comment]
@matthewelwell nodejs does not automatically clean up `setInterval()` when they go out of scope, and does not have any kind of destructor which we can override ([Ref](https://stackoverflow.com/questions/54395197/does-node-js-cancel-setinterval-automatically)).

Therefore if the library maintains any kind of state (like a setInterval), it must also provide a method to cleanup this state. (This is a common pattern for nodejs libraries)

Since python explicitly provides a destructor method (`__del__`), we wouldn't need something like this in the python client.

**Comment by matthewelwell** [comment]
@thebongy gotcha, thanks very much for the comprehensive response (and apologies for my limited understanding of NodeJS!). 

I'll approve this now and can update our documentation with the required information.

**Review by matthewelwell — APPROVED** [review]

**Comment by matthewelwell** [comment]
Released in v2.2.1

**Pull request merged**
